services:
  nexus:
    image: sonatype/nexus3:3.76.1
    container_name: nexus
    restart: unless-stopped
    ports:
      - 38081:8081  # web ui
      - 20000:20000 # used in docker-proxy
      - 30000:30000 # used in docker-group
    volumes:
      - nexus_data:/nexus-data
    networks:
      - nexus_network

volumes:
  nexus_data:

networks:
  nexus_network:
    driver: bridge
