services:
  mysql:
    image: mysql:lts
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-conf:/etc/mysql/conf.d
    networks:
      - default-network

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - default-network

  oracledb:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracledb
    restart: unless-stopped
    environment:
      ORACLE_PWD: system
    networks:
      - default-network
    ports:
      - 1521:1521
    volumes:
      - oracledb-data:/opt/oracle/oradata

  mongodb:
    image: mongo:8.0.3
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - mongodb-conf:/data/configdb
      - mongodb-logs:/data/log
    networks:
      - default-network

  redis:
    image: redis:7.4.1
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - default-network

  rabbitmq-cluster-01:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq-cluster-01
    restart: unless-stopped
    ports:
      - 15671:15672
      - 5671:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: secret
      RABBITMQ_NODENAME: rabbitmq@rabbitmq-cluster-01
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_mqtt && 
        rabbitmq-plugins enable rabbitmq_stream &&
        rabbitmq-server
      "
    volumes:
      - rabbitmq-cluster-01-data:/var/lib/rabbitmq
    networks:
      - default-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq-cluster-02:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq-cluster-02
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: secret
      RABBITMQ_NODENAME: rabbitmq@rabbitmq-cluster-02
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_mqtt && 
        rabbitmq-plugins enable rabbitmq_stream &&
        rabbitmq-server
      "
    volumes:
      - rabbitmq-cluster-02-data:/var/lib/rabbitmq
    networks:
      - default-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq-cluster-03:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq-cluster-03
    restart: unless-stopped
    ports:
      - 15673:15672
      - 5673:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: secret
      RABBITMQ_NODENAME: rabbitmq@rabbitmq-cluster-03
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_mqtt && 
        rabbitmq-plugins enable rabbitmq_stream &&
        rabbitmq-server
      "
    volumes:
      - rabbitmq-cluster-03-data:/var/lib/rabbitmq
    networks:
      - default-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq-cluster-setup:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq-cluster-setup
    depends_on:
      rabbitmq-cluster-01:
        condition: service_healthy
      rabbitmq-cluster-02:
        condition: service_healthy
      rabbitmq-cluster-03:
        condition: service_healthy
    environment:
      RABBITMQ_ERLANG_COOKIE: secret
    command: >
      bash -c "
        sleep 5 &&

        rabbitmqctl -n rabbitmq@rabbitmq-cluster-02 stop_app &&
        rabbitmqctl -n rabbitmq@rabbitmq-cluster-02 join_cluster rabbitmq@rabbitmq-cluster-01 &&
        rabbitmqctl -n rabbitmq@rabbitmq-cluster-02 start_app &&

        rabbitmqctl -n rabbitmq@rabbitmq-cluster-03 stop_app &&
        rabbitmqctl -n rabbitmq@rabbitmq-cluster-03 join_cluster rabbitmq@rabbitmq-cluster-01 &&
        rabbitmqctl -n rabbitmq@rabbitmq-cluster-03 start_app &&

        echo 'initial rabbitmq cluster success...'
      "
    networks:
      - default-network
    volumes:
      - rabbitmq-cluster-setup-data:/var/lib/rabbitmq
  
  kafka-kraft-01:
    image: apache/kafka:4.2.0
    container_name: kafka-kraft-01
    hostname: kafka-kraft-01
    restart: unless-stopped
    ports:
      - 9091:9091
    networks:
      - default-network
    volumes:
      - kafka-kraft-01-data:/var/lib/kafka/data
      - kafka-kraft-01-secrets:/etc/kafka/secrets
      - kafka-kraft-01-conf:/mnt/shared/config
    environment:
      CLUSTER_ID: kraft-docker
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:19091,PLAINTEXT://0.0.0.0:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.22.36.195:9091
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft-01:19091,2@kafka-kraft-02:19092,3@kafka-kraft-03:19093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9091"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


  kafka-kraft-02:
    image: apache/kafka:4.2.0
    container_name: kafka-kraft-02
    hostname: kafka-kraft-02
    restart: unless-stopped
    ports:
      - 9092:9092
    networks:
      - default-network
    volumes:
      - kafka-kraft-02-data:/var/lib/kafka/data
      - kafka-kraft-02-secrets:/etc/kafka/secrets
      - kafka-kraft-02-conf:/mnt/shared/config
    environment:
      CLUSTER_ID: kraft-docker
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:19092,PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.22.36.195:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft-01:19091,2@kafka-kraft-02:19092,3@kafka-kraft-03:19093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  kafka-kraft-03:
    image: apache/kafka:4.2.0
    container_name: kafka-kraft-03
    hostname: kafka-kraft-03
    restart: unless-stopped
    ports:
      - 9093:9093
    networks:
      - default-network
    volumes:
      - kafka-kraft-03-data:/var/lib/kafka/data
      - kafka-kraft-03-secrets:/etc/kafka/secrets
      - kafka-kraft-03-conf:/mnt/shared/config
    environment:
      CLUSTER_ID: kraft-docker
      KAFKA_NODE_ID: 3
      KAFKA_BROKER_ID: 3
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:19093,PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.22.36.195:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft-01:19091,2@kafka-kraft-02:19092,3@kafka-kraft-03:19093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9093"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    restart: unless-stopped
    container_name: kafbat-ui
    depends_on:
      kafka-kraft-01:
        condition: service_healthy
      kafka-kraft-02:
        condition: service_healthy
      kafka-kraft-03:
        condition: service_healthy
    networks:
      - default-network
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: kafka-kraft-docker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-kraft-01:9091,kafka-kraft-02:9092,kafka-kraft-03:9093

  es-cluster-01:
    container_name: es-cluster-01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    restart: unless-stopped
    volumes:
      - es-cluster-01-data:/usr/share/elasticsearch/data
    networks:
      - default-network
    ports:
      - 9200:9200
    environment:
      node.name: es-cluster-01
      cluster.name: elastic-cluster-docker
      cluster.initial_master_nodes: es-cluster-01,es-cluster-02,es-cluster-03
      discovery.seed_hosts: es-cluster-02,es-cluster-03
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      xpack.ml.use_auto_machine_memory_percent: true
      ELASTIC_PASSWORD: elastic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9200"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  es-cluster-02:
    container_name: es-cluster-02
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    restart: unless-stopped
    volumes:
      - es-cluster-02-data:/usr/share/elasticsearch/data
    networks:
      - default-network
    ports:
      - 9300:9200
    environment:
      node.name: es-cluster-02
      cluster.name: elastic-cluster-docker
      cluster.initial_master_nodes: es-cluster-01,es-cluster-02,es-cluster-03
      discovery.seed_hosts: es-cluster-01,es-cluster-03
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      xpack.ml.use_auto_machine_memory_percent: true
      ELASTIC_PASSWORD: elastic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9200"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  es-cluster-03:
    container_name: es-cluster-03
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    restart: unless-stopped
    volumes:
      - es-cluster-03-data:/usr/share/elasticsearch/data
    networks:
      - default-network
    ports:
      - 9400:9200
    environment:
      node.name: es-cluster-03
      cluster.name: elastic-cluster-docker
      cluster.initial_master_nodes: es-cluster-01,es-cluster-02,es-cluster-03
      discovery.seed_hosts: es-cluster-01,es-cluster-02
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      xpack.ml.use_auto_machine_memory_percent: true
      ELASTIC_PASSWORD: elastic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9200"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.16.1
    restart: unless-stopped
    depends_on:
      es-cluster-01:
        condition: service_healthy
      es-cluster-02:
        condition: service_healthy
      es-cluster-03:
        condition: service_healthy
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - default-network
    ports:
      - 5601:5601
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: '["http://es-cluster-01:9200","http://es-cluster-02:9200","http://es-cluster-03:9200"]'
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: kibana
    mem_limit: 1073741824
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  
  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    container_name: logstash
    restart: unless-stopped
    ports:
      - 5044:5044
      - 12000:12000
    depends_on:
      es-cluster-01:
        condition: service_healthy
      es-cluster-02:
        condition: service_healthy
      es-cluster-03:
        condition: service_healthy
    user: root
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
      LOGSTASH_INTERNAL_PASSWORD: elastic
    networks:
      - default-network
  
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    restart: unless-stopped
    ports:
      - 4317:4317 
      - 4318:4318
    networks:
      - default-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: example
      KC_BOOTSTRAP_ADMIN_PASSWORD: example
    ports:
      - 8888:8080
    command: start-dev

  prometheus:
    image: prom/prometheus:v3.11.3
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
    ports:
      - 9999:9090
    networks:
      - default-network

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: grafana
    networks:
      - default-network

networks:
  default-network:

volumes:
  mysql-data:
  mysql-conf:
  postgres-data:
  mongodb-data:
  mongodb-conf:
  mongodb-logs:
  oracledb-data:
  redis-data:
  rabbitmq-cluster-01-data:
  rabbitmq-cluster-02-data:
  rabbitmq-cluster-03-data:
  rabbitmq-cluster-setup-data:
  kafka-kraft-01-data:
  kafka-kraft-01-secrets:
  kafka-kraft-01-conf:
  kafka-kraft-02-data:
  kafka-kraft-02-secrets:
  kafka-kraft-02-conf:
  kafka-kraft-03-data:
  kafka-kraft-03-secrets:
  kafka-kraft-03-conf:
  es-cluster-01-data:
  es-cluster-02-data:
  es-cluster-03-data:
  kibana-data:
  prometheus-data:
