services:
  mysql:
    image: mysql:lts
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-conf:/etc/mysql/conf.d
    networks:
      - default-network

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - default-network

  oracledb:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracledb
    restart: unless-stopped
    environment:
      ORACLE_PWD: system
    networks:
      - default-network
    ports:
      - 1521:1521
    volumes:
      - oracledb-data:/opt/oracle/oradata

  mongodb:
    image: mongo:8.0.3
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - mongodb-conf:/data/configdb
      - mongodb-logs:/data/log
    networks:
      - default-network

  redis:
    image: redis:7.4.1
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - default-network

  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: secret
    command: >
      bash -c "
        rabbitmq-plugins enable rabbitmq_mqtt && 
        rabbitmq-plugins enable rabbitmq_stream &&
        rabbitmq-server
      "
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - default-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    hostname: zookeeper
    container_name: zookeeper
    restart: unless-stopped
    networks:
      - default-network
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
  
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    container_name: kafka
    restart: unless-stopped
    networks:
      - default-network
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.22.36.195:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG4J_LOGGERS: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s  

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    restart: unless-stopped
    container_name: kafbat-ui
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - default-network
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.1
    restart: unless-stopped
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - default-network
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      node.name: elasticsearch
      cluster.name: elasticsearch
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      xpack.license.self_generated.type: basic
      xpack.ml.use_auto_machine_memory_percent: true
      ELASTIC_PASSWORD: elastic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9200"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s
  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:9.4.1
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - default-network
    ports:
      - 5601:5601
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: kibana
    mem_limit: 1073741824
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
  
  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    container_name: logstash
    restart: unless-stopped
    ports:
      - 5044:5044
      - 12000:12000
    depends_on:
      elasticsearch:
        condition: service_healthy
    user: root
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
      LOGSTASH_INTERNAL_PASSWORD: elastic
    networks:
      - default-network

  seata-server:
    container_name: seata-server
    image: apache/seata-server:2.2.0
    restart: unless-stopped
    ports:
      - 7091:7091
      - 8091:8091
    environment:
      STORE_MODE: file
      SEATA_PORT: 8091
    networks:
      - default-network

  sentinel:
    build: 
      context: ./sentinel
      dockerfile: Dockerfile
    image: sentinel:1.8.9
    container_name: sentinel
    restart: unless-stopped
    ports:
      - 15566:15566
    networks:
      - default-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    restart: unless-stopped
    ports:
      - 4317:4317 
      - 4318:4318
    networks:
      - default-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: example
      KC_BOOTSTRAP_ADMIN_PASSWORD: example
    ports:
      - 8888:8080
    command: start-dev

  prometheus:
    image: prom/prometheus:v3.11.3
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
    ports:
      - 9999:9090
    networks:
      - default-network

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: grafana
    networks:
      - default-network

networks:
  default-network:

volumes:
  mysql-data:
  mysql-conf:
  postgres-data:
  mongodb-data:
  mongodb-conf:
  mongodb-logs:
  oracledb-data:
  redis-data:
  rabbitmq-data:
  kafka-data:
  kafka-secrets:
  kafka-conf:
  elasticsearch-data:
  kibana-data:
  prometheus-data:
  nacos-logs: