services:
  xxl-cluster-01:
    depends_on:
      xxl-cluster-mysql:
        condition: service_healthy
    build: 
      context: .
      dockerfile: ./Dockerfile-xxl-job
    image: xxl-job:2.4.2
    container_name: xxl-cluster-01
    ports:
      - 18888:8080
    networks:
      - xxl_cluster_network
  xxl-cluster-02:
    depends_on:
      xxl-cluster-mysql:
        condition: service_healthy
    build: 
      context: .
      dockerfile: ./Dockerfile-xxl-job
    image: xxl-job:2.4.2
    container_name: xxl-cluster-02
    ports:
      - 28888:8080
    networks:
      - xxl_cluster_network
  xxl-cluster-03:
    depends_on:
      xxl-cluster-mysql:
        condition: service_healthy
    build: 
      context: .
      dockerfile: ./Dockerfile-xxl-job
    image: xxl-job:2.4.2
    container_name: xxl-cluster-03
    ports:
      - 38888:8080
    networks:
      - xxl_cluster_network

  xxl-cluster-mysql:
    build:
      context: .
      dockerfile: ./Dockerfile-mysql
    image: xxl-job-mysql:9.1.0
    container_name: xxl-cluster-mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "xxl_job"
      MYSQL_USER: "xxl_job"
      MYSQL_PASSWORD: "xxl_job"
    volumes:
      - "xxl_cluster_mysql_data:/var/lib/mysql"
      - "xxl_cluster_mysql_conf.d:/etc/mysql/conf.d"
    networks:
      - xxl_cluster_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  xxl_cluster_network:
    driver: bridge

volumes:
  xxl_cluster_mysql_data:
  xxl_cluster_mysql_conf.d: