services:
  xxl-01:
    depends_on:
      xxl-mysql-cluster:
        condition: service_healthy
    build: 
      context: .
      dockerfile: ./Dockerfile-xxl-job
    image: xxl-job:2.4.2
    container_name: xxl-01
    ports:
      - 18888:8080
    networks:
      - xxl_cluster_network
  xxl-02:
    depends_on:
      xxl-mysql-cluster:
        condition: service_healthy
    build: 
      context: .
      dockerfile: ./Dockerfile-xxl-job
    image: xxl-job:2.4.2
    container_name: xxl-02
    ports:
      - 28888:8080
    networks:
      - xxl_cluster_network
  xxl-03:
    depends_on:
      xxl-mysql-cluster:
        condition: service_healthy
    build: 
      context: .
      dockerfile: ./Dockerfile-xxl-job
    image: xxl-job:2.4.2
    container_name: xxl-03
    ports:
      - 38888:8080
    networks:
      - xxl_cluster_network

  xxl-mysql-cluster:
    build:
      context: .
      dockerfile: ./Dockerfile-mysql
    image: xxl-job-mysql:9.1.0
    container_name: xxl-mysql-cluster
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "xxl_job"
      MYSQL_USER: "xxl_job"
      MYSQL_PASSWORD: "xxl_job"
    ports:
      - "7606:3306"
    volumes:
      - "xxl_mysql_cluster_data:/var/lib/mysql"
      - "xxl_mysql_cluster_conf.d:/etc/mysql/conf.d"
    networks:
      - xxl_cluster_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  xxl_cluster_network:
    driver: bridge

volumes:
  xxl_mysql_cluster_data:
  xxl_mysql_cluster_conf.d: