services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    restart: unless-stopped
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=es01:9200,es02:9200,es03:9200
    ports:
      - 9411:9411
    networks:
      - zipkin_network
      - elastic_elastic_network

networks:
  zipkin_network:
    driver: bridge
  elastic_elastic_network:
    external: true