services:
  postgres:
    image: postgres:13.18
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: 'example'
      POSTGRES_PASSWORD: 'example' 
      POSTGRES_DB: 'example'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres_network
volumes:
  postgres_data:
  
networks:
  postgres_network: 
    driver: bridge
