services:
  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    networks:
      - grafana_network
    ports:
      - 9100:9100

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    image: prometheus:v3.1.0
    container_name: prometheus
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    volumes:
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - grafana_network
      - mysqld_mysql_network
      - postgresql_postgres_network
      - rabbitmq_cluster_rabbitmq_cluster_network
      - kafka_cluster_kafka_cluster_network
      - elastic_elastic_network

  alert-manager:
    build:
      context: ./alert_manager
      dockerfile: Dockerfile
    image: alertmanager:v0.27.0
    container_name: alert-manager
    env_file:
      - path: ../.env
        required: true
    volumes:
      - alert_manager_data:/alertmanager
    networks:
      - grafana_network
    ports:
      - 9093:9093

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    networks:
      - grafana_network

volumes:
  prometheus_data:
  alert_manager_data:

networks:
  grafana_network:
  mysqld_mysql_network:
    external: true
  postgresql_postgres_network:
    external: true
  rabbitmq_cluster_rabbitmq_cluster_network:
    external: true
  kafka_cluster_kafka_cluster_network:
    external: true
  elastic_elastic_network:
    external: true
