#!/bin/bash

set -e

mkdir -p /opt/oracle/oradata/recovery_area

sqlplus /nolog <<- EOF
	CONNECT SYS/SYS AS SYSDBA
	ALTER SYSTEM SET db_recovery_file_dest_size = 10G;
	ALTER SYSTEM SET db_recovery_file_dest = '/opt/oracle/oradata/recovery_area' scope=spfile;
	SHUTDOWN IMMEDIATE;
	STARTUP MOUNT;
	ALTER DATABASE ARCHIVELOG;
	ALTER DATABASE OPEN;
	ARCHIVE LOG LIST;
	exit;
EOF

sqlplus SYS/SYS@//localhost:1521/FREE as sysdba <<- EOF
  ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
  ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;
  exit;
EOF

sqlplus SYS/SYS@//localhost:1521/FREE as sysdba <<- EOF
  CREATE TABLESPACE LOGMINER_TBS DATAFILE '/opt/oracle/oradata/FREE/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
  exit;
EOF

sqlplus SYS/SYS@//localhost:1521/FREEPDB1 as sysdba <<- EOF
  CREATE TABLESPACE LOGMINER_TBS DATAFILE '/opt/oracle/oradata/FREE/FREEPDB1/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
  exit;
EOF

sqlplus SYS/SYS@//localhost:1521/FREE as sysdba <<- EOF
  CREATE USER c##replica IDENTIFIED BY replica DEFAULT TABLESPACE LOGMINER_TBS QUOTA UNLIMITED ON LOGMINER_TBS CONTAINER=ALL;

  GRANT CREATE SESSION TO c##replica CONTAINER=ALL;
  GRANT SET CONTAINER TO c##replica CONTAINER=ALL;
  GRANT SELECT ON V_\$DATABASE TO c##replica CONTAINER=ALL;
  GRANT FLASHBACK ANY TABLE TO c##replica CONTAINER=ALL;
  GRANT SELECT ANY TABLE TO c##replica CONTAINER=ALL;
  GRANT SELECT_CATALOG_ROLE TO c##replica CONTAINER=ALL;
  GRANT EXECUTE_CATALOG_ROLE TO c##replica CONTAINER=ALL;
  GRANT SELECT ANY TRANSACTION TO c##replica CONTAINER=ALL;
  GRANT SELECT ANY DICTIONARY TO c##replica CONTAINER=ALL;
  GRANT LOGMINING TO c##replica CONTAINER=ALL;

  GRANT CREATE TABLE TO c##replica CONTAINER=ALL;
  GRANT LOCK ANY TABLE TO c##replica CONTAINER=ALL;
  GRANT CREATE SEQUENCE TO c##replica CONTAINER=ALL;

  GRANT EXECUTE ON DBMS_LOGMNR TO c##replica CONTAINER=ALL;
  GRANT EXECUTE ON DBMS_LOGMNR_D TO c##replica CONTAINER=ALL;
  GRANT SELECT ON V_\$LOGMNR_LOGS TO c##replica CONTAINER=ALL;
  GRANT SELECT ON V_\$LOGMNR_CONTENTS TO c##replica CONTAINER=ALL;
  GRANT SELECT ON V_\$LOGFILE TO c##replica CONTAINER=ALL;
  GRANT SELECT ON V_\$ARCHIVED_LOG TO c##replica CONTAINER=ALL;
  GRANT SELECT ON V_\$ARCHIVE_DEST_STATUS TO c##replica CONTAINER=ALL;

  exit;
EOF

sqlplus SYS/SYS@//localhost:1521/FREEPDB1 as sysdba <<- EOF
  CREATE USER debezium IDENTIFIED BY debezium;
  GRANT CONNECT TO debezium;
  GRANT CREATE SESSION TO debezium;
  GRANT CREATE TABLE TO debezium;
  GRANT CREATE SEQUENCE to debezium;
  ALTER USER debezium QUOTA 100M on users;
  exit;
EOF