services:
  seata-server:
    container_name: seata-server
    image: apache/seata-server:2.2.0
    hostname: seata-server
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      - STORE_MODE=file
      - SEATA_PORT=8091
    networks:
      - seata_network

networks:
  seata_network:
    driver: bridge