FROM bellsoft/liberica-openjdk-debian:17.0.11-cds

LABEL maintainer="opensnail"
LABEL app-name="snail-job-server"
LABEL description="SnailJob is a high performance distributed task scheduler and retry management center"

ENV TZ=Asia/Shanghai LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom -XX:+HeapDumpOnOutOfMemoryError -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xmx1g -Xms1g -Xmn512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1HeapRegionSize=8M"
# ENV PARAMS="--spring.datasource.username=snail_job --spring.datasource.password=snail_job  --spring.datasource.url=jdbc:mysql://snail-cluster-mysql:3306/snail_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver"
ENV PARAMS="--spring.datasource.username=snail_job --spring.datasource.password=snail_job  --spring.datasource.url=jdbc:postgresql://snail-cluster-postgresql:5432/snail_job?useSSL=false --spring.datasource.driver-class-name=org.postgresql.Driver"

WORKDIR /snailjob/server
ADD ./snail-job-server-exec.jar app.jar

EXPOSE 8080
EXPOSE 1788

VOLUME /snailjob/server/data/log

SHELL ["/bin/bash", "-c"]
ENTRYPOINT java $JAVA_OPTS -jar app.jar $PARAMS
