services:
  snail-cluster-01:
    depends_on:
      snail-cluster-mysql:
        condition: service_healthy
      snail-cluster-postgresql:
        condition: service_healthy
    container_name: snail-cluster-01
    env_file:
      - path: ../.env
        required: true
    build:
      context: .
      dockerfile: ./Dockerfile-snail-job
    image: snail-job:1.2.0
    volumes:
      - snail_cluster_01_log:/snailjob/server/data/log
    ports:
      - 18080:8080
      - 11788:1788
    networks:
      - snail_cluster_network

  snail-cluster-02:
    depends_on:
      snail-cluster-mysql:
        condition: service_healthy
      snail-cluster-postgresql:
        condition: service_healthy
    container_name: snail-cluster-02
    env_file:
      - path: ../.env
        required: true
    build:
      context: .
      dockerfile: ./Dockerfile-snail-job
    image: snail-job:1.2.0
    volumes:
      - snail_cluster_02_log:/snailjob/server/data/log
    ports:
      - 28080:8080
      - 21788:1788
    networks:
      - snail_cluster_network

  snail-cluster-03:
    depends_on:
      snail-cluster-mysql:
        condition: service_healthy
      snail-cluster-postgresql:
        condition: service_healthy
    container_name: snail-cluster-03
    env_file:
      - path: ../.env
        required: true
    build:
      context: .
      dockerfile: ./Dockerfile-snail-job
    image: snail-job:1.2.0
    volumes:
      - snail_cluster_03_log:/snailjob/server/data/log
    ports:
      - 38080:8080
      - 31788:1788
    networks:
      - snail_cluster_network

  snail-cluster-postgresql:
    build:
      context: .
      dockerfile: ./Dockerfile-postgresql
    image: snail-job-postgresql:13.18
    container_name: snail-cluster-postgresql
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    environment:
      POSTGRES_USER: "snail_job"
      POSTGRES_PASSWORD: "snail_job"
      POSTGRES_DB: "snail_job"
    volumes:
      - "snail_cluster_postgresql_data:/var/lib/postgresql/data"
    networks:
      - snail_cluster_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  snail-cluster-mysql:
    build:
      context: .
      dockerfile: ./Dockerfile-mysql
    image: snail-job-mysql:9.1.0
    container_name: snail-cluster-mysql
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "snail_job"
      MYSQL_USER: "snail_job"
      MYSQL_PASSWORD: "snail_job"
    volumes:
      - "snail_cluster_mysql_data:/var/lib/mysql"
      - "snail_cluster_mysql_conf.d:/etc/mysql/conf.d"
    networks:
      - snail_cluster_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  snail_cluster_network:
    driver: bridge

volumes:
  snail_cluster_01_log:
  snail_cluster_02_log:
  snail_cluster_03_log:
  snail_cluster_mysql_data:
  snail_cluster_mysql_conf.d:
  snail_cluster_postgresql_data:
