FROM mysql:9.1.0

USER root

ADD ./snail_job_mysql.sql /docker-entrypoint-initdb.d/snail_job_mysql.sql
RUN chown -R mysql:mysql /docker-entrypoint-initdb.d/snail_job_mysql.sql

EXPOSE 3306

CMD ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]