services:
  nacos-cluster-1:
    hostname: nacos-cluster-1
    container_name: nacos-cluster-1
    image: nacos/nacos-server:v2.4.3
    volumes:
      - nacos_cluster_1_logs:/home/nacos/logs
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    env_file:
      - ./env/nacos-cluster-hostname.env
      - path: ../.env
        required: true
      
    depends_on:
      nacos-cluster-mysql:
        condition: service_healthy
    networks:
      - nacos_cluster_network

  nacos-cluster-2:
    hostname: nacos-cluster-2
    image: nacos/nacos-server:v2.4.3
    container_name: nacos-cluster-2
    volumes:
      - nacos_cluster_2_logs:/home/nacos/logs
    ports:
      - "17848:7848"
      - "18848:8848"
      - "19848:9848"
      - "19849:9849"
    env_file:
      - ./env/nacos-cluster-hostname.env
      - path: ../.env
        required: true
    depends_on:
      nacos-cluster-mysql:
        condition: service_healthy
    networks:
      - nacos_cluster_network

  nacos-cluster-3:
    hostname: nacos-cluster-3
    image: nacos/nacos-server:v2.4.3
    container_name: nacos-cluster-3
    volumes:
      - nacos_cluster_3_logs:/home/nacos/logs
    ports:
      - "27848:7848"
      - "28848:8848"
      - "29848:9848"
      - "29849:9849"
    env_file:
      - ./env/nacos-cluster-hostname.env
      - path: ../.env
        required: true
    depends_on:
      nacos-cluster-mysql:
        condition: service_healthy
    networks:
      - nacos_cluster_network

  nacos-cluster-mysql:
    container_name: nacos-cluster-mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nacos-mysql/mysql:5.7.44
    env_file:
      - ./env/mysql.env
      - path: ../.env
        required: true
    volumes:
      - nacos_cluster_mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - nacos_cluster_network

volumes:
  nacos_cluster_mysql_data:
  nacos_cluster_1_logs:
  nacos_cluster_2_logs:
  nacos_cluster_3_logs:

networks:
  nacos_cluster_network:
    driver: bridge