services:
  hive-postgres:
    image: postgres:13.18
    container_name: hive-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: "hive_metastore"
      POSTGRES_USER: "hive"
      POSTGRES_PASSWORD: "hive"
    ports:
      - 15432:5432
    volumes:
      - hive_metastore_db:/var/lib/postgresql
    networks:
      - hive_network

  hive-metastore:
    image: apache/hive:4.0.1
    depends_on:
      - hive-postgres
    container_name: hive-metastore
    restart: on-failure
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: "metastore"
      SERVICE_OPTS:
        "-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-postgres:5432/hive_metastore
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive"
    ports:
      - "9083:9083"
    volumes:
      - hive_warehouse:/opt/hive/data/warehouse
      - type: bind
        source: ./postgresql-42.7.4.jar
        target: /opt/hive/lib/postgres.jar
    networks:
      - hive_network

  hiveserver2:
    image: apache/hive:4.0.1
    depends_on:
      - hive-metastore
    container_name: hiveserver2
    restart: on-failure
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: "-Xmx1G -Dhive.metastore.uris=thrift://hive-metastore:9083"
      IS_RESUME: "true"
      SERVICE_NAME: "hiveserver2"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - hive_warehouse:/opt/hive/data/warehouse
    networks:
      - hive_network

volumes:
  hive_metastore_db:
  hive_warehouse:

networks:
  hive_network:
    driver: bridge
