services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
    user: flink:flink
    container_name: jobmanager
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: jobmanager
    networks: 
      - flink_network

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    user: flink:flink
    container_name: taskmanager
    restart: unless-stopped
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=4
    command: taskmanager
    networks: 
      - flink_network

networks:
  flink_network:
    driver: bridge