services:
  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
    user: flink:flink
    container_name: jobmanager
    ports:
      - 8081:8081
    environment:
      - | 
        FLINK_PROPERTIES=
        JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: jobmanager
    networks: 
      - flink_network

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    user: flink:flink
    container_name: taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2  
    command: taskmanager
    networks: 
      - flink_network

networks:
  flink_network:
    driver: bridge