services:
  kafka-controller-01:
    image: apache/kafka:3.9.0
    container_name: kafka-controller-01
    restart: unless-stopped
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_controller_data_01:/var/lib/kafka/data
      - kafka_controller_secrets_01:/etc/kafka/secrets
      - kafka_controller_config_01:/mnt/shared/config
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-controller-02:
    image: apache/kafka:3.9.0
    container_name: kafka-controller-02
    restart: unless-stopped
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_controller_data_02:/var/lib/kafka/data
      - kafka_controller_secrets_02:/etc/kafka/secrets
      - kafka_controller_config_02:/mnt/shared/config
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-controller-03:
    image: apache/kafka:3.9.0
    container_name: kafka-controller-03
    restart: unless-stopped
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_controller_data_03:/var/lib/kafka/data
      - kafka_controller_secrets_03:/etc/kafka/secrets
      - kafka_controller_config_03:/mnt/shared/config
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-broker-01:
    build: 
      context: .
      dockerfile: Dockerfile
    image: kafka:3.9.0
    container_name: kafka-broker-01
    restart: unless-stopped
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_broker_data_01:/var/lib/kafka/data
      - kafka_broker_secrets_01:/etc/kafka/secrets
      - kafka_broker_config_01:/mnt/shared/config
    ports:
      - 19092:19092
      - 11001:11001
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: "PLAINTEXT://:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://10.100.133.11:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OPTS: -javaagent:/opt/kafka/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar=11001:/opt/kafka/jmx_exporter/kafka-broker.yml
    depends_on:
      - kafka-controller-01
      - kafka-controller-02
      - kafka-controller-03

  kafka-broker-02:
    build: 
        context: .
        dockerfile: Dockerfile
    image: kafka:3.9.0
    container_name: kafka-broker-02
    restart: unless-stopped
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_broker_data_02:/var/lib/kafka/data
      - kafka_broker_secrets_02:/etc/kafka/secrets
      - kafka_broker_config_02:/mnt/shared/config
    ports:
      - 29092:29092
      - 11002:11002
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: "PLAINTEXT://:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://10.100.133.11:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OPTS: -javaagent:/opt/kafka/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar=11002:/opt/kafka/jmx_exporter/kafka-broker.yml
    depends_on:
      - kafka-controller-01
      - kafka-controller-02
      - kafka-controller-03

  kafka-broker-03:
    build: 
        context: .
        dockerfile: Dockerfile
    image: kafka:3.9.0
    container_name: kafka-broker-03
    restart: unless-stopped
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_broker_data_03:/var/lib/kafka/data
      - kafka_broker_secrets_03:/etc/kafka/secrets
      - kafka_broker_config_03:/mnt/shared/config
    ports:
      - 39092:39092
      - 11003:11003
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: "PLAINTEXT://:39092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://10.100.133.11:39092"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OPTS: -javaagent:/opt/kafka/jmx_exporter/jmx_prometheus_javaagent-1.1.0.jar=11003:/opt/kafka/jmx_exporter/kafka-broker.yml
    depends_on:
      - kafka-controller-01
      - kafka-controller-02
      - kafka-controller-03

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    restart: unless-stopped
    container_name: kafbat-ui
    depends_on:
      - kafka-broker-01
      - kafka-broker-02
      - kafka-broker-03
    networks:
      - kafka_cluster_network
    ports:
      - 7777:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: kafka-docker-01
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-01:19092
      KAFKA_CLUSTERS_1_NAME: kafka-docker-02
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka-broker-02:29092
      KAFKA_CLUSTERS_2_NAME: kafka-docker-03
      KAFKA_CLUSTERS_2_BOOTSTRAPSERVERS: kafka-broker-03:39092
      

networks:
  kafka_cluster_network:
    driver: bridge

volumes:
  kafka_controller_data_01:
  kafka_controller_secrets_01:
  kafka_controller_config_01:
  kafka_controller_data_02:
  kafka_controller_secrets_02:
  kafka_controller_config_02:
  kafka_controller_data_03:
  kafka_controller_secrets_03:
  kafka_controller_config_03:
  kafka_broker_data_01:
  kafka_broker_secrets_01:
  kafka_broker_config_01:
  kafka_broker_data_02:
  kafka_broker_secrets_02:
  kafka_broker_config_02:
  kafka_broker_data_03:
  kafka_broker_secrets_03:
  kafka_broker_config_03:
