services:
  kafka-controller-01:
    image: apache/kafka:3.9.0
    container_name: kafka-controller-01
    networks:
      - kafka_cluster_network    
    volumes:
      - kafka_controller_data_01:/var/lib/kafka/data
      - kafka_controller_secrets_01:/etc/kafka/secrets
      - kafka_controller_config_01:/mnt/shared/config
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-controller-02:
    image: apache/kafka:3.9.0
    container_name: kafka-controller-02
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_controller_data_02:/var/lib/kafka/data
      - kafka_controller_secrets_02:/etc/kafka/secrets
      - kafka_controller_config_02:/mnt/shared/config  
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-controller-03:
    image: apache/kafka:3.9.0
    container_name: kafka-controller-03
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_controller_data_03:/var/lib/kafka/data
      - kafka_controller_secrets_03:/etc/kafka/secrets
      - kafka_controller_config_03:/mnt/shared/config
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-broker-01:
    image: apache/kafka:3.9.0
    container_name: kafka-broker-01
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_broker_data_01:/var/lib/kafka/data
      - kafka_broker_secrets_01:/etc/kafka/secrets
      - kafka_broker_config_01:/mnt/shared/config
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-01:19092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - kafka-controller-01
      - kafka-controller-02
      - kafka-controller-03

  kafka-broker-02:
    image: apache/kafka:3.9.0
    container_name: kafka-broker-02
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_broker_data_02:/var/lib/kafka/data
      - kafka_broker_secrets_02:/etc/kafka/secrets
      - kafka_broker_config_02:/mnt/shared/config
    ports:
      - 39092:9092
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-02:19092,PLAINTEXT_HOST://localhost:39092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - kafka-controller-01
      - kafka-controller-02
      - kafka-controller-03

  kafka-broker-03:
    image: apache/kafka:3.9.0
    container_name: kafka-broker-03
    networks:
      - kafka_cluster_network
    volumes:
      - kafka_broker_data_03:/var/lib/kafka/data
      - kafka_broker_secrets_03:/etc/kafka/secrets
      - kafka_broker_config_03:/mnt/shared/config
    ports:
      - 49092:9092
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-03:19092,PLAINTEXT_HOST://localhost:49092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-01:9093,2@kafka-controller-02:9093,3@kafka-controller-03:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - kafka-controller-01
      - kafka-controller-02
      - kafka-controller-03

networks:
  kafka_cluster_network:
    driver: bridge

volumes:
  kafka_controller_data_01:
  kafka_controller_secrets_01:
  kafka_controller_config_01:
  kafka_controller_data_02:
  kafka_controller_secrets_02:
  kafka_controller_config_02:
  kafka_controller_data_03:
  kafka_controller_secrets_03:
  kafka_controller_config_03:
  kafka_broker_data_01:
  kafka_broker_secrets_01:
  kafka_broker_config_01:
  kafka_broker_data_02:
  kafka_broker_secrets_02:
  kafka_broker_config_02:
  kafka_broker_data_03:
  kafka_broker_secrets_03:
  kafka_broker_config_03: