services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=transmission
      - PASS=transmission
    volumes:
      - transmission_config:/config
      - transmission_downloads:/downloads
      - transmission_watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: on-failure
    networks:
      - transmission_network

networks:
  transmission_network:
    driver: bridge

volumes:
  transmission_config:
  transmission_downloads:
  transmission_watch: