services:
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    ports:
      - 5540:5540
    networks:
      - redis_cluster_network

  redis-master:
    image: redis:7.4.1
    container_name: redis-master
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    user: redis
    ports:
      - 6379:6379
    volumes:
      - redis_master_data:/data
    networks:
      - redis_cluster_network
    command:
      - "redis-server"
      - "--appendonly yes"
      - "--repl-diskless-load on-empty-db"
      - "--protected-mode no"
      - "--replica-announce-ip ${LOCAL_IP}"
      - "--replica-announce-port 6379"

  redis-slave-01:
    image: redis:7.4.1
    container_name: redis-slave-01
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    user: redis
    ports:
      - 6380:6380
    volumes:
      - redis_slave_01_data:/data
    networks:
      - redis_cluster_network
    depends_on:
      - redis-master
    command:
      - "redis-server"
      - "--port 6380"
      - "--replicaof ${LOCAL_IP} 6379"
      - "--appendonly yes"
      - "--repl-diskless-load on-empty-db"
      - "--protected-mode no"
      - "--replica-announce-ip ${LOCAL_IP}"
      - "--replica-announce-port 6380"

  redis-slave-02:
    image: redis:7.4.1
    container_name: redis-slave-02
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    user: redis
    ports:
      - 6381:6381
    volumes:
      - redis_slave_02_data:/data
    networks:
      - redis_cluster_network
    depends_on:
      - redis-master
    command:
      - "redis-server"
      - "--port 6381"
      - "--replicaof ${LOCAL_IP} 6379"
      - "--appendonly yes"
      - "--repl-diskless-load on-empty-db"
      - "--protected-mode no"
      - "--replica-announce-ip ${LOCAL_IP}"
      - "--replica-announce-port 6381"

  redis-sentinel-01:
    image: redis:7.4.1
    container_name: redis-sentinel-01
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    ports:
      - 26379:26379
    volumes:
      - redis_sentinel_01_data:/data
    networks:
      - redis_cluster_network
    depends_on:
      - redis-master
    command: >
      bash -c '
        > /etc/sentinel.conf &&
        echo "protected-mode no" >> /etc/sentinel.conf &&
        echo "port 26379" >> /etc/sentinel.conf &&
        echo "sentinel announce-ip ${LOCAL_IP}" >> /etc/sentinel.conf &&
        echo "sentinel announce-port 26379" >> /etc/sentinel.conf &&
        echo "sentinel monitor redis-docker ${LOCAL_IP} 6379 2" >> /etc/sentinel.conf &&
        echo "sentinel resolve-LOCAL_IPnames yes" >> /etc/sentinel.conf &&
        echo "sentinel down-after-milliseconds redis-docker 10000" >> /etc/sentinel.conf &&
        echo "sentinel failover-timeout redis-docker 10000" >> /etc/sentinel.conf &&
        echo "sentinel parallel-syncs redis-docker 1" >> /etc/sentinel.conf &&
        redis-sentinel /etc/sentinel.conf --sentinel
      '

  redis-sentinel-02:
    image: redis:7.4.1
    container_name: redis-sentinel-02
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    ports:
      - 26380:26380
    volumes:
      - redis_sentinel_02_data:/data
    networks:
      - redis_cluster_network
    depends_on:
      - redis-master
    command: >
      bash -c '
        > /etc/sentinel.conf &&
        echo "protected-mode no" >> /etc/sentinel.conf &&
        echo "port 26380" >> /etc/sentinel.conf &&
        echo "sentinel announce-ip ${LOCAL_IP}" >> /etc/sentinel.conf &&
        echo "sentinel announce-port 26380" >> /etc/sentinel.conf &&
        echo "sentinel monitor redis-docker ${LOCAL_IP} 6379 2" >> /etc/sentinel.conf &&
        echo "sentinel resolve-LOCAL_IPnames yes" >> /etc/sentinel.conf &&
        echo "sentinel down-after-milliseconds redis-docker 10000" >> /etc/sentinel.conf &&
        echo "sentinel failover-timeout redis-docker 10000" >> /etc/sentinel.conf &&
        echo "sentinel parallel-syncs redis-docker 2" >> /etc/sentinel.conf &&
        redis-sentinel /etc/sentinel.conf --sentinel
      '

  redis-sentinel-03:
    image: redis:7.4.1
    container_name: redis-sentinel-03
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true
    ports:
      - 26381:26381
    volumes:
      - redis_sentinel_03_data:/data
    networks:
      - redis_cluster_network
    depends_on:
      - redis-master
    command: >
      bash -c '
        > /etc/sentinel.conf &&
        echo "protected-mode no" >> /etc/sentinel.conf &&
        echo "port 26381" >> /etc/sentinel.conf &&
        echo "sentinel announce-ip ${LOCAL_IP}" >> /etc/sentinel.conf &&
        echo "sentinel announce-port 26381" >> /etc/sentinel.conf &&
        echo "sentinel monitor redis-docker ${LOCAL_IP} 6379 2" >> /etc/sentinel.conf &&
        echo "sentinel resolve-LOCAL_IPnames yes" >> /etc/sentinel.conf &&
        echo "sentinel down-after-milliseconds redis-docker 10000" >> /etc/sentinel.conf &&
        echo "sentinel failover-timeout redis-docker 10000" >> /etc/sentinel.conf &&
        echo "sentinel parallel-syncs redis-docker 3" >> /etc/sentinel.conf &&
        redis-sentinel /etc/sentinel.conf --sentinel
      '

volumes:
  redis_master_data:
  redis_slave_01_data:
  redis_slave_02_data:
  redis_sentinel_01_data:
  redis_sentinel_02_data:
  redis_sentinel_03_data:

networks:
  redis_cluster_network:
    driver: bridge
